version: '3.7'
services:

  orthology:
    #image: orthology-api
    depends_on:
      - "postgresql"
    command: [ "./wait-for-db.sh", "postgresql:5432", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar", "--server.port=8902", "--spring.profiles.active=docker"]
    build: ./
    ports:
      - "8902:8902"
    environment:
      - TRACKER_PORT=8902
      - TRACKER_POSTGRESQL_DB_HOST=postgresql
      - TRACKER_POSTGRESQL_DB_PORT=5432
    networks:
      production:

  postgresql:
    image: rwilsonebi/orthology-db
    environment:
      - POSTGRES_PASSWORD=orthology_admin
      - POSTGRES_USER=orthology_admin
      - POSTGRES_DB=orthologydata
    ports:
      - "6062:5432"
    networks:
      production:

# declare the network ressource
# this will allow you to use service discovery and address a container by its name from within the network
networks:
  production:

