apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-ortholog-service-reference-db
  name: api-ortholog-service-reference-db
  namespace: mi-reference-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ortholog-service-reference-db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-ortholog-service-reference-db
    spec:
      containers:
      - image: rwilsonebi/orthology-api:latest
        imagePullPolicy: Always
        name: api-ortholog-service-reference-db
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /orthology-api
        - name: EBI_PROXY
          value: "true"
        - name: REFERENCE_SERVICE
          value: "true"
        - name: POSTGRESQL_DB_HOST
          value: reference-database
        - name: POSTGRESQL_DB_PORT
          value: "5432"
        - name: REDEPLOY_KEY
          value: "STRING_REPLACED_DURING_REDEPLOY"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: { }