apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-service-dev
  name: api-service-dev
  namespace: mi-orthology-dev
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31016
  selector:
    app: api-service-dev
  #
  # Note:
  # To use an Ingress Controller
  # the type should be set as ClusterIP
  # rather than NodePort or LoadBalancer.
  #
  type: NodePort
