apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-service-dev
  name: api-service-dev
  namespace: mi-orthology-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service-dev
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-service-dev
    spec:
      containers:
      - image: rwilsonebi/orthology-api:latest
        imagePullPolicy: Always
        name: api-service-dev
        env:
#        - name: SERVER_SERVLET_CONTEXT_PATH
#          value: /orthology-api
        - name: POSTGRESQL_DB_HOST
          value: orthology-database
        - name: POSTGRESQL_DB_PORT
          value: "5432"
        - name: REDEPLOY_KEY
          value: "STRING_REPLACED_DURING_REDEPLOY"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
